# Generated by Django 3.1.7 on 2021-04-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_mobile_no', models.CharField(max_length=10)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_appointment', models.DateField()),
            ],
        ),
    ]
